### ISSUE TITLE
Generated data almost one year old

### ISSUE THREAD

**Issue by cibermanchego** [swimlane/pyattck-data#124]
Hi, I don't know if I'm understanding correctly how it works, but I see in the generated files shared in the S3 buckets that last update was in April 2022.
`{"last_updated": "2022-04-15T03:32:59.971457`

Is that expected behavior? I noticed because looking for information about the actor 'Polonium' there is no entry in the data.

**Comment by MSAdministrator** [comment]
Hey @cibermanchego I believe you are looking at the old version of the generated data. The new one `https://swimlane-pyattck.s3.us-west-2.amazonaws.com/generated_attck_data_v2.json` is used by latest versions of pyattck and is updated every 15 days or so.
