### ISSUE TITLE
AWS S3 Storage Access broken 

### ISSUE THREAD

**Issue by MSAdministrator** [swimlane/pyattck-data#147]
Currently we cannot access these links to download data which in turn breaks pyattck.

- Enterprise ATT&CK JSON (merged with external data) - https://swimlane-pyattck.s3.us-west-2.amazonaws.com/merged_enterprise_attck_v1.json
- Pre-ATT&CK JSON (merged with external data) - https://swimlane-pyattck.s3.us-west-2.amazonaws.com/merged_pre_attck_v1.json
- Mobile ATT&CK JSON (merged with external data) - https://swimlane-pyattck.s3.us-west-2.amazonaws.com/merged_mobile_attck_v1.json
- ICS ATT&CK JSON (merged with external data) - https://swimlane-pyattck.s3.us-west-2.amazonaws.com/merged_ics_attck_v1.json
- NIST Controls JSON - https://swimlane-pyattck.s3.us-west-2.amazonaws.com/merged_nist_controls_v1.json
- Generated NIST JSON - https://swimlane-pyattck.s3.us-west-2.amazonaws.com/attck_to_nist_controls.json
- generated_attck_data.json - https://swimlane-pyattck.s3.us-west-2.amazonaws.com/generated_attck_data.json
- generated_attck_data_v2.json - https://swimlane-pyattck.s3.us-west-2.amazonaws.com/generated_attck_data_v2.json

**Comment by MSAdministrator** [comment]
This is currently impacting these issues in the pyattck repository:

https://github.com/swimlane/pyattck/issues/136
https://github.com/swimlane/pyattck/issues/137
https://github.com/swimlane/pyattck/issues/138

**Comment by larntz** [comment]
@MSAdministrator I think this is fixed, but I'm still having an issue accessing https://swimlane-pyattck.s3.us-west-2.amazonaws.com/generated_attck_data_v2.json. 

Can you upload the files again so we can see if that fixes and be sure the issue is resolved?

**Comment by MSAdministrator** [comment]
I reuploaded and this seems to be resolved. Thanks for the quick work
